// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxwspdxtfisosuzricgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4d3NwZHh0Zmlzb3N1enJpY2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTAxMjUsImV4cCI6MjA2NjIyNjEyNX0.oakoyjUDRdPt1cwSO4YkM7LEe_9p339r0e0ld0wAPz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);